name: Failing Workflow

on: [push]

jobs:
  fail-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a failing command
        run: exit 1
